name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Install Supabase CLI
        run: |
          rm -rf supabase supabase-cli supabase.tar.gz
          curl -L \
            "https://github.com/supabase/cli/releases/latest/download/supabase_linux_amd64.tar.gz" \
            -o supabase.tar.gz
          mkdir supabase-cli
          tar -xvf supabase.tar.gz -C supabase-cli
          sudo mv supabase-cli/supabase /usr/local/bin/supabase
          supabase --version
          
      - name: Check Supabase CLI
        run: supabase --version 
        
      - name: Supabase DB Push 
        run: supabase db push --project-dir supabase --db-url "${{ secrets.SUPABASE_DEV_URL }}"

      - name: Deploy do Vercel (dev)
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN_DEV }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_DEV }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          npx vercel pull --yes --environment=development --token "$VERCEL_TOKEN"
          npx vercel deploy --yes --token "$VERCEL_TOKEN"

