name: Dev Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Supabase CLI
        run: |
          curl -fsSL https://get.supabase.com/cli/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Check Supabase CLI
        run: supabase --version

      - name: Supabase DB Push
        run: supabase db push --db-url "${{ secrets.SUPABASE_DEV_URL }}"

      - name: Vercel Deploy
        run: |
          npm install -g vercel
          vercel deploy --token ${{ secrets.VERCEL_TOKEN }} --yes
